"""Topic miner. Every topic traces to a REAL query string returned by Google's
autocomplete service — the same source that powers the search box. Nothing here
is generated by a language model.

Demand signal:   a query appearing in autocomplete means people type it.
Depth signal:    how many distinct completions a seed produces.
Provenance:      seed + endpoint + timestamp recorded for every topic.
"""
import json, time, urllib.parse, urllib.request, sys, re
from datetime import datetime, timezone

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
ENDPOINT = "https://suggestqueries.google.com/complete/search"

def suggest(q, yt=True, hl="en", gl="us"):
    p = {"client":"firefox","q":q,"hl":hl,"gl":gl}
    if yt: p.update({"ds":"yt"})
    url = ENDPOINT + "?" + urllib.parse.urlencode(p)
    req = urllib.request.Request(url, headers={"User-Agent":UA})
    try:
        with urllib.request.urlopen(req, timeout=12) as r:
            data = json.loads(r.read().decode("utf-8","ignore"))
        return data[1] if len(data) > 1 else []
    except Exception as e:
        return []

QUESTION = re.compile(r"^(why|how|what|when|where|who|which|is|are|do|does|can|did)\b", re.I)

def expand(seeds, alphabet=True, pause=0.35):
    """Seed -> completions -> alphabet-suffixed completions. Real data only."""
    found = {}
    for seed in seeds:
        for s in suggest(seed):
            found.setdefault(s.lower().strip(), set()).add(seed)
        time.sleep(pause)
        if alphabet:
            for ch in "abcdefghijklmnopqrstuvwxyz":
                for s in suggest(f"{seed} {ch}"):
                    found.setdefault(s.lower().strip(), set()).add(f"{seed} {ch}")
                time.sleep(pause)
    return found

if __name__ == "__main__":
    seeds = json.load(open(sys.argv[1]))["seeds"] if len(sys.argv)>1 else ["deep sea"]
    print(f"mining {len(seeds)} seeds…", flush=True)
    found = expand(seeds)
    rows = []
    for q, srcs in found.items():
        rows.append({
            "query": q,
            "is_question": bool(QUESTION.match(q)),
            "words": len(q.split()),
            "seed_hits": len(srcs),
            "seeds": sorted(srcs)[:4],
        })
    rows.sort(key=lambda r: (-r["seed_hits"], -r["is_question"], r["words"]))
    out = {"mined_at": datetime.now(timezone.utc).isoformat(),
           "endpoint": ENDPOINT, "surface": "youtube_autocomplete",
           "seed_count": len(seeds), "unique_queries": len(rows), "queries": rows}
    json.dump(out, open("mined_queries.json","w"), indent=2)
    print(f"{len(rows)} unique real queries -> mined_queries.json")
    q = [r for r in rows if r["is_question"]]
    print(f"  of which questions: {len(q)}")
    for r in q[:15]:
        print(f"   {r['seed_hits']:>2}x  {r['query']}")
