/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CreaturesIndexRouteImport } from './routes/creatures.index'
import { Route as CreaturesCreatureRouteImport } from './routes/creatures.$creature'
import { Route as MethodsIndexRouteImport } from './routes/methods.index'
import { Route as MethodsMethodRouteImport } from './routes/methods.$method'
import { Route as QuestionsIndexRouteImport } from './routes/questions.index'
import { Route as QuestionsQuestionRouteImport } from './routes/questions.$question'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as ZonesIndexRouteImport } from './routes/zones.index'
import { Route as ZonesZoneRouteImport } from './routes/zones.$zone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaturesIndexRoute = CreaturesIndexRouteImport.update({
  id: '/creatures/',
  path: '/creatures/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreaturesCreatureRoute = CreaturesCreatureRouteImport.update({
  id: '/creatures/$creature',
  path: '/creatures/$creature',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsIndexRoute = MethodsIndexRouteImport.update({
  id: '/methods/',
  path: '/methods/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsMethodRoute = MethodsMethodRouteImport.update({
  id: '/methods/$method',
  path: '/methods/$method',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsQuestionRoute = QuestionsQuestionRouteImport.update({
  id: '/questions/$question',
  path: '/questions/$question',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesIndexRoute = ZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesZoneRoute = ZonesZoneRouteImport.update({
  id: '/zones/$zone',
  path: '/zones/$zone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/creatures/$creature': typeof CreaturesCreatureRoute
  '/methods/$method': typeof MethodsMethodRoute
  '/questions/$question': typeof QuestionsQuestionRoute
  '/zones/$zone': typeof ZonesZoneRoute
  '/creatures/': typeof CreaturesIndexRoute
  '/methods/': typeof MethodsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/creatures/$creature': typeof CreaturesCreatureRoute
  '/methods/$method': typeof MethodsMethodRoute
  '/questions/$question': typeof QuestionsQuestionRoute
  '/zones/$zone': typeof ZonesZoneRoute
  '/creatures': typeof CreaturesIndexRoute
  '/methods': typeof MethodsIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/watch': typeof WatchIndexRoute
  '/zones': typeof ZonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/admin': typeof AdminRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/explore': typeof ExploreRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/creatures/$creature': typeof CreaturesCreatureRoute
  '/methods/$method': typeof MethodsMethodRoute
  '/questions/$question': typeof QuestionsQuestionRoute
  '/zones/$zone': typeof ZonesZoneRoute
  '/creatures/': typeof CreaturesIndexRoute
  '/methods/': typeof MethodsIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/zones/': typeof ZonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/admin'
    | '/editorial-policy'
    | '/explore'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/creatures/$creature'
    | '/methods/$method'
    | '/questions/$question'
    | '/zones/$zone'
    | '/creatures/'
    | '/methods/'
    | '/questions/'
    | '/watch/'
    | '/zones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/admin'
    | '/editorial-policy'
    | '/explore'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/creatures/$creature'
    | '/methods/$method'
    | '/questions/$question'
    | '/zones/$zone'
    | '/creatures'
    | '/methods'
    | '/questions'
    | '/watch'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/admin'
    | '/editorial-policy'
    | '/explore'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/creatures/$creature'
    | '/methods/$method'
    | '/questions/$question'
    | '/zones/$zone'
    | '/creatures/'
    | '/methods/'
    | '/questions/'
    | '/watch/'
    | '/zones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AdminRoute: typeof AdminRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  ExploreRoute: typeof ExploreRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CreaturesCreatureRoute: typeof CreaturesCreatureRoute
  MethodsMethodRoute: typeof MethodsMethodRoute
  QuestionsQuestionRoute: typeof QuestionsQuestionRoute
  ZonesZoneRoute: typeof ZonesZoneRoute
  CreaturesIndexRoute: typeof CreaturesIndexRoute
  MethodsIndexRoute: typeof MethodsIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
  ZonesIndexRoute: typeof ZonesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatures/': {
      id: '/creatures/'
      path: '/creatures'
      fullPath: '/creatures/'
      preLoaderRoute: typeof CreaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatures/$creature': {
      id: '/creatures/$creature'
      path: '/creatures/$creature'
      fullPath: '/creatures/$creature'
      preLoaderRoute: typeof CreaturesCreatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods/': {
      id: '/methods/'
      path: '/methods'
      fullPath: '/methods/'
      preLoaderRoute: typeof MethodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods/$method': {
      id: '/methods/$method'
      path: '/methods/$method'
      fullPath: '/methods/$method'
      preLoaderRoute: typeof MethodsMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$question': {
      id: '/questions/$question'
      path: '/questions/$question'
      fullPath: '/questions/$question'
      preLoaderRoute: typeof QuestionsQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/': {
      id: '/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof ZonesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones/$zone': {
      id: '/zones/$zone'
      path: '/zones/$zone'
      fullPath: '/zones/$zone'
      preLoaderRoute: typeof ZonesZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AdminRoute: AdminRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  ExploreRoute: ExploreRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CreaturesCreatureRoute: CreaturesCreatureRoute,
  MethodsMethodRoute: MethodsMethodRoute,
  QuestionsQuestionRoute: QuestionsQuestionRoute,
  ZonesZoneRoute: ZonesZoneRoute,
  CreaturesIndexRoute: CreaturesIndexRoute,
  MethodsIndexRoute: MethodsIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
  ZonesIndexRoute: ZonesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
