#!/usr/bin/env python3
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[2]
FINAL=ROOT/'production/scripts/final'
PLAIN=ROOT/'production/scripts/plaintext'

SUPPLEMENTS={
1:("The question I want the viewer to keep", "When the next bizarre animal appears, pause before naming it. Restore the habitat, then identify the constraint. That single habit turns shock into curiosity. It is also how this channel avoids becoming a slideshow of grotesque close-ups: every image has to earn its explanation through depth, scale, condition, and function."),
2:("What a surface demonstration cannot reproduce", "A balloon, syringe, or crushed container can demonstrate gas compression, but it cannot reproduce the molecular biology of a living deep-sea animal. That matters because dramatic classroom demonstrations often become the whole explanation. They show why trapped gas is vulnerable. They do not show how enzymes keep working, how membranes maintain the right flexibility, how nervous tissue responds, or why one species tolerates a pressure change that harms another. The video should say this plainly before the final payoff. The simple experiment is a doorway into the biology, not a substitute for it. That keeps the episode accessible without pretending the deep ocean is solved by one piece of physics."),
3:("The headline I would trust", "A trustworthy headline names the animal and the observation. It does not turn one body into a message from the planet. If a species is unknown, say that. If the capture method could explain the ascent, include it. If the animal was dead or injured, include that too. The difference may feel less dramatic, but it gives the audience something they can verify. For a channel trying to build watch time over months, that credibility compounds. A viewer who catches one exaggerated claim may not trust the next nineteen accurate ones. The human decision here is to leave the uncertainty in the story and make the investigation itself entertaining."),
4:("The fear reveal", "Near the end, the edit should reveal the actual size and normal distance of each animal that appeared frightening in close-up. That reveal is not a debunk. It is the episode's central contrast. The audience gets the image that earned the click, then receives the context that keeps the channel from becoming a fear factory. The anglerfish can remain visually disturbing while also being a small, remote specialist. A dragonfish can keep its impossible-looking teeth while the narration explains why losing prey is costly. The final comparison should place environmental danger beside animal danger. Pressure, cold, darkness, and distance win by a wide margin. The creatures are the memorable faces of the deep; they are rarely the main hazard to humans."),
5:("A camera-light warning", "Every red-creature shot should carry a small note when artificial white light is doing the revealing. Without that note, the footage quietly teaches the opposite of the biology. The audience sees a vivid red animal and hears that red is camouflage, which can sound contradictory. The correction is visual: show the same body under a simplified deep-water light spectrum, then restore the ROV lamps. That lets viewers watch the color change as an effect of illumination rather than accept it as a verbal claim. It also gives the editor a repeatable technique for future color episodes. Whenever a video depends on what an animal looks like, ask what light produced the image. Color is not a fixed label attached to a body. It is an interaction among pigment, available wavelengths, viewing angle, and the sensor recording it."),
6:("The organ problem", "The most convincing transparent animals are never uniformly invisible. Their digestive systems, eyes, reproductive tissue, or recent meals can betray them. That imperfection is the story. Evolution does not get to remove every organ that scatters light. It works around the organs the animal still needs. Some species narrow or reposition opaque structures. Some use mirrors or pigments. Some stay small. Some orient their bodies to present less visible area. The video should pause on an animal whose gut remains visible and explain that transparency is a reduction in detection, not a magic cloak. This makes the adaptation feel more biological and less like a visual effect. It also prevents us from claiming that a transparent creature disappears equally well to every predator, wavelength, and viewing angle. The animal is playing probabilities, not becoming absent."),
7:("A depth chart without villains", "The final depth chart should replace the usual monster lineup with ecological roles. Put a migrator beside a predator in the twilight zone. Put a gelatinous drifter beside an anglerfish in the midnight zone. Put a sea cucumber, scavenging crustacean, and microbe beside the dramatic abyssal fish. In the hadal section, show the snailfish record and then continue the chart with animals that live deeper than confirmed fish. The visual message becomes diversity under constraint rather than escalating evil. That change is structural, not cosmetic. It keeps this episode from repeating the ranked-list format and gives the viewer a reason to stay to the bottom of the chart: the expected final monster never arrives. The payoff is a softer animal and a harder biological limit."),
8:("The missing majority", "Any twenty-creature list will still leave out most of the deep ocean. Microbes drive chemical transformations. Tiny crustaceans dominate many samples. Delicate gelatinous animals are underrepresented when nets destroy them. Burrowing animals can remain invisible to cameras. Parasites and symbionts add relationships that a species list misses entirely. The video should acknowledge that bias instead of using a handful of charismatic animals as the whole ecosystem. One short sequence can compare methods: a net catches sturdy bodies, an ROV records behavior in a narrow lighted field, acoustics reveal movement at scale, and environmental DNA detects traces without showing the animal itself. Each method sees a different ocean. The list is therefore an invitation into the habitats, not a census. That distinction matters for future automation too: new episodes should expand underrepresented roles and methods, not just repeat the creatures with the strongest thumbnails."),
9:("The audience gets to disagree", "The closing should invite viewers to name the feature that triggers their fear—teeth, eyes, size, movement, parasitism, or resemblance to something familiar. That response gives the channel useful topic intelligence without pretending there is one objective winner. It also creates follow-up episodes with a real editorial reason: not 'another scary animal,' but a closer look at why a specific adaptation reads as threatening to humans. The pinned comment can separate personal fear from actual danger and link to the broader explainer about why deep-sea creatures look strange. The channel gains engagement while reinforcing the scientific boundary. That is the kind of monetization-minded choice worth keeping: a prompt that produces comments and sequels without manufacturing a false fact."),
10:("The scale check", "Before the closing, compare Challenger Deep with the average ocean depth and with the height of a familiar mountain only if the comparison uses current, sourced values. The visual should not imply that a mountain could literally be dropped into the trench without considering sea level, shape, and the uneven bottom. It is an analogy for scale, not a survey method. The strongest ending returns to measurement: the deepest known point remains a value scientists refine, not a mystical coordinate beyond uncertainty. That gives the next expedition something meaningful to improve."),
11:("The owner check", "Before approval, I need to listen for how the narrator says the genus name and the depth record. A technically correct script can still sound careless if the scientific name is mangled or the number rushes past without context. The final master should let the animal move long enough for the viewer to see that it is not a cartoon character attached to fins."),
12:("The phrase we are retiring", "The final script must not call the frilled shark unchanged for tens of millions of years. The lineage is ancient; the living animal is not a time capsule. Retiring that sentence costs a cleaner clickbait claim, but it protects the entire channel from a correction that would be easy for viewers to make."),
13:("The disclosure in the percentage", "When the percentage appears on screen, the label should read 'animals observed in MBARI's ROV dataset,' not 'all deep-sea animals.' That extra line is small, but it separates a real study result from an invented universal census. The narration should also distinguish generated light from fluorescence before showing any glowing image."),
14:("The final size card", "The last measurement card should show mass, total length, and mantle length as separate fields, with a note that preservation and damage affect comparison. A projected maximum belongs on a different card. The audience can still imagine a larger animal; the video simply refuses to label that imagination as a specimen record."),
15:("The publication-day recheck", "Any visitor count must be removed or rechecked on the day of publication because additional descents can make it obsolete. The script deliberately avoids building the title around that count. The stable story is engineering, repeatability, and measured depth. That choice makes the episode durable instead of accurate only on the day it was drafted."),
16:("The continuity shot", "Use the same section of skeleton in each phase so the audience can see the habitat changing around it. Do not cut from one unrelated whale fall to another and imply a single time-lapse. If external footage is admitted, the caption must identify when different sites or expeditions are being compared. The original diagram remains the safest continuity device."),
17:("The word on screen", "When the title uses 'farms,' the first on-screen definition should say that the crab promotes and harvests bacterial growth; it does not prove conscious planning. That one sentence keeps the curiosity hook while showing the evidence behind it. The episode should also name the species, because not every yeti crab uses the same body surface or habitat."),
18:("The temperature card", "Use 'can exceed 340 degrees Celsius' rather than turning one value into the temperature of every black smoker. Pair it with the pressure explanation and a visible mixing gradient. The animals belong around the gradient, not inside the hottest fluid. That correction should survive into the thumbnail, description, and chapters so the packaging does not overstate what the script carefully explains."),
19:("The record label", "Every time the depth record appears, the edit must say FILMED or CAUGHT. The two labels are the episode's spine. The species identification for the filmed animal remains cautious because no specimen was recovered. That is not a flaw in the study; it is the correct limit of video evidence. The final title and description should preserve that distinction."),
20:("The observation window", "The final master should show the ROV lights briefly and explain that the camera changes the scene it records. That makes the footage feel more honest and gives context to animal behavior near the vehicle. The zone boundaries should remain approximate labels, while the depth gauge moves continuously. The viewer leaves with a habitat, not a set of artificial boxes."),
}


def wc(text): return len(re.findall(r"\b[\w’'-]+\b",text))
def ts(seconds):
    seconds=int(round(seconds)); return f'{seconds//60:02d}:{seconds%60:02d}'

for seq,path in enumerate(sorted(FINAL.glob('[0-9][0-9]-*.md')),1):
    text=path.read_text(); title,body=SUPPLEMENTS[seq]
    marker='\n### What to notice in the edit\n'
    if f'### {title}\n' not in text:
        text=text.replace(marker,f'\n### {title}\n\n{body}\n{marker}',1)
    narr=re.search(r'## Narration\n(.*?)(?=\n## Human fingerprint gate)',text,re.S).group(1)
    sections=[]
    for part in re.split(r'(?m)^### ',narr)[1:]:
        name,section_body=part.split('\n',1); sections.append((name.strip(),section_body.strip()))
    plain='\n\n'.join(b.replace('[HUMAN] ','') for _,b in sections).strip()+'\n'
    count=wc(plain); duration=count/145*60
    text=re.sub(r'\*\*Word count:\*\*\s*\d+',f'**Word count:** {count}',text)
    text=re.sub(r'\*\*Estimated narration:\*\*\s*[^\n]+',f'**Estimated narration:** {int(duration//60)}m {int(round(duration%60)):02d}s at 145 WPM',text)
    elapsed=0; chapters=[]
    for name,b in sections:
        chapters.append(f'- {ts(elapsed)} {name}'); elapsed+=wc(b)/145*60
    text=re.sub(r'## Chapters\n\n.*?(?=\n## Sources)','## Chapters\n\n'+'\n'.join(chapters)+'\n',text,flags=re.S)
    path.write_text(text); (PLAIN/path.with_suffix('.txt').name).write_text(plain)
    print(f'{path.name}: {count}')
